### ISSUE TITLE
Error when saving output of get_node_names()

### ISSUE THREAD

**Issue by realmarcin** [AnacletoLAB/ensmallen_graph#63]
Using this simple ensmallen 0.5.2 -based script:
https://github.com/kbaseIncubator/KE_KG/blob/main/src/embeddings/graphs_stats_degrees_nodes.py

to generate node degrees and node labels. Running this script on a graph that I am sharing with you in slack, gives this graph summary and an error when saving the results of the get_node_labels() call with np.savetxt(), see below:

The undirected graph Graph has 169784 nodes and 2596040 unweighted edges, of which 13026 are self-loops. The graph is quite sparse as it has a density of 0.00018 and has 2 connected components, where the component with most nodes has 169782 nodes and the component with the least nodes has 2 nodes. The graph median node degree is 9, the mean node degree is 30.50 and the node degree mode is 7. The top 5 most central nodes are Virus_topology:linear_contig (degree 96796), NCBItaxon:duplodnaviria;heunggongvirae;uroviricota;caudoviricetes;caudovirales;;; (degree 81390), Contig_length:5 (degree 74875), Contig_length:4 (degree 63612) and Virus_topology:direct_terminal_repeats_(dtrs) (degree 30497).
Traceback (most recent call last):
  File "/global/u1/m/marcinj/graphs/embiggen/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1424, in savetxt
    v = format % tuple(row) + newline
TypeError: must be real number, not numpy.str_

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/embeddings/graphs_stats_degrees_nodes.py", line 25, in <module>
    np.savetxt("merged_imgvr_mg_nodes.tsv", nodes, delimiter="\t")
  File "<__array_function__ internals>", line 6, in savetxt
  File "/global/u1/m/marcinj/graphs/embiggen/venv/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1428, in savetxt
    % (str(X.dtype), format))
TypeError: Mismatch between array dtype ('<U173') and format specifier ('%.18e')

**Comment by realmarcin** [comment]
This was a numpy error and solved by adding a fmt parameter to savetxt.
E.g.:
np.savetxt("node_ids.tsv", node_ids, delimiter="\t", fmt="%s")
